apiVersion: v1
kind: Pod
metadata:
  name: prime-api
  labels:
    app: prime-api
spec:
  containers:
    - image: asia.gcr.io/graphic-bonus-302708/krustlet-example/prime-api:v1
      imagePullPolicy: Always
      name: prime-api
      ports:
        - containerPort: 8080
          hostPort: 8080
  nodeSelector:
    beta.kubernetes.io/os: linux
    beta.kubernetes.io/arch: wasm32-wascc
  tolerations:
    - key: "node.kubernetes.io/network-unavailable"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "kubernetes.io/arch"
      operator: "Equal"
      value: "wasm32-wascc"
      effect: "NoExecute"
    - key: "kubernetes.io/arch"
      operator: "Equal"
      value: "wasm32-wascc"
      effect: "NoSchedule"
